/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Page_content_inner.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Page_content_inner::Page_content_inner()
{
    m_Id = "";
    m_Type = "";
    m_Text = "";
    m_ShapeType = "";
    m_Angle = 0.0;
    m_SymbolRes = "";
    
}

void Page_content_inner::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Page_content_inner::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Page_content_inner::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Page_content_inner" : pathPrefix;

                 
    
    /* Box */ {
        const std::vector<double>& value = m_Box;
        const std::string currentValuePath = _pathPrefix + ".box";
                
        
        if (value.size() < 4)
        {
            success = false;
            msg << currentValuePath << ": must have at least 4 elements;";
        }
        if (value.size() > 4)
        {
            success = false;
            msg << currentValuePath << ": must have at most 4 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const double& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
                         
    
    /* Points */ {
        const std::vector<double>& value = m_Points;
        const std::string currentValuePath = _pathPrefix + ".points";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const double& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
    
    return success;
}

bool Page_content_inner::operator==(const Page_content_inner& rhs) const
{
    return
    
    
    (getId() == rhs.getId())
     &&
    
    (getType() == rhs.getType())
     &&
    
    (getBox() == rhs.getBox())
     &&
    
    (getText() == rhs.getText())
     &&
    
    (getShapeType() == rhs.getShapeType())
     &&
    
    (getAngle() == rhs.getAngle())
     &&
    
    (getSymbolRes() == rhs.getSymbolRes())
     &&
    
    (getPoints() == rhs.getPoints())
    
    
    ;
}

bool Page_content_inner::operator!=(const Page_content_inner& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Page_content_inner& o)
{
    j = nlohmann::json::object();
    j["id"] = o.m_Id;
    j["type"] = o.m_Type;
    j["box"] = o.m_Box;
    j["text"] = o.m_Text;
    j["shapeType"] = o.m_ShapeType;
    j["angle"] = o.m_Angle;
    j["symbolRes"] = o.m_SymbolRes;
    j["points"] = o.m_Points;
    
}

void from_json(const nlohmann::json& j, Page_content_inner& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("type").get_to(o.m_Type);
    j.at("box").get_to(o.m_Box);
    j.at("text").get_to(o.m_Text);
    j.at("shapeType").get_to(o.m_ShapeType);
    j.at("angle").get_to(o.m_Angle);
    j.at("symbolRes").get_to(o.m_SymbolRes);
    j.at("points").get_to(o.m_Points);
    
}

std::string Page_content_inner::getId() const
{
    return m_Id;
}
void Page_content_inner::setId(std::string const& value)
{
    m_Id = value;
}
std::string Page_content_inner::getType() const
{
    return m_Type;
}
void Page_content_inner::setType(std::string const& value)
{
    m_Type = value;
}
std::vector<double> Page_content_inner::getBox() const
{
    return m_Box;
}
void Page_content_inner::setBox(std::vector<double> const value)
{
    m_Box = value;
}
std::string Page_content_inner::getText() const
{
    return m_Text;
}
void Page_content_inner::setText(std::string const& value)
{
    m_Text = value;
}
std::string Page_content_inner::getShapeType() const
{
    return m_ShapeType;
}
void Page_content_inner::setShapeType(std::string const& value)
{
    m_ShapeType = value;
}
double Page_content_inner::getAngle() const
{
    return m_Angle;
}
void Page_content_inner::setAngle(double const value)
{
    m_Angle = value;
}
std::string Page_content_inner::getSymbolRes() const
{
    return m_SymbolRes;
}
void Page_content_inner::setSymbolRes(std::string const& value)
{
    m_SymbolRes = value;
}
std::vector<double> Page_content_inner::getPoints() const
{
    return m_Points;
}
void Page_content_inner::setPoints(std::vector<double> const value)
{
    m_Points = value;
}


} // namespace org::openapitools::server::model

