/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Page.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Page::Page()
{
    m_PageId = "";
    
}

void Page::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Page::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Page::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Page" : pathPrefix;

             
    
    /* Content */ {
        const std::vector<org::openapitools::server::model::Page_content_inner>& value = m_Content;
        const std::string currentValuePath = _pathPrefix + ".content";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::Page_content_inner& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".content") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool Page::operator==(const Page& rhs) const
{
    return
    
    
    (getPageId() == rhs.getPageId())
     &&
    
    (getContent() == rhs.getContent())
    
    
    ;
}

bool Page::operator!=(const Page& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Page& o)
{
    j = nlohmann::json::object();
    j["pageId"] = o.m_PageId;
    j["content"] = o.m_Content;
    
}

void from_json(const nlohmann::json& j, Page& o)
{
    j.at("pageId").get_to(o.m_PageId);
    j.at("content").get_to(o.m_Content);
    
}

std::string Page::getPageId() const
{
    return m_PageId;
}
void Page::setPageId(std::string const& value)
{
    m_PageId = value;
}
std::vector<org::openapitools::server::model::Page_content_inner> Page::getContent() const
{
    return m_Content;
}
void Page::setContent(std::vector<org::openapitools::server::model::Page_content_inner> const& value)
{
    m_Content = value;
}


} // namespace org::openapitools::server::model

