/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Page.h
 *
 * 
 */

#ifndef Page_H_
#define Page_H_


#include <string>
#include "Page_content_inner.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Page
{
public:
    Page();
    virtual ~Page() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Page& rhs) const;
    bool operator!=(const Page& rhs) const;

    /////////////////////////////////////////////
    /// Page members

    /// <summary>
    /// 
    /// </summary>
    std::string getPageId() const;
    void setPageId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::Page_content_inner> getContent() const;
    void setContent(std::vector<org::openapitools::server::model::Page_content_inner> const& value);

    friend  void to_json(nlohmann::json& j, const Page& o);
    friend  void from_json(const nlohmann::json& j, Page& o);
protected:
    std::string m_PageId;

    std::vector<org::openapitools::server::model::Page_content_inner> m_Content;

    
};

} // namespace org::openapitools::server::model

#endif /* Page_H_ */
