/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Room.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Room::Room()
{
    m_Id = "";
    
}

void Room::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Room::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Room::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Room" : pathPrefix;

         
    
    /* Id */ {
        const std::string& value = m_Id;
        const std::string currentValuePath = _pathPrefix + ".id";
                
        
        if (value.length() < 5)
        {
            success = false;
            msg << currentValuePath << ": must be at least 5 characters long;";
        }
        if (value.length() > 5)
        {
            success = false;
            msg << currentValuePath << ": must be at most 5 characters long;";
        }

    }
         
    
    /* Pages */ {
        const std::vector<org::openapitools::server::model::Page>& value = m_Pages;
        const std::string currentValuePath = _pathPrefix + ".pages";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::Page& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".pages") && success;
 
                i++;
            }
        }

    }
    
    return success;
}

bool Room::operator==(const Room& rhs) const
{
    return
    
    
    (getId() == rhs.getId())
     &&
    
    (getPages() == rhs.getPages())
    
    
    ;
}

bool Room::operator!=(const Room& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Room& o)
{
    j = nlohmann::json::object();
    j["id"] = o.m_Id;
    j["pages"] = o.m_Pages;
    
}

void from_json(const nlohmann::json& j, Room& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("pages").get_to(o.m_Pages);
    
}

std::string Room::getId() const
{
    return m_Id;
}
void Room::setId(std::string const& value)
{
    m_Id = value;
}
std::vector<org::openapitools::server::model::Page> Room::getPages() const
{
    return m_Pages;
}
void Room::setPages(std::vector<org::openapitools::server::model::Page> const& value)
{
    m_Pages = value;
}


} // namespace org::openapitools::server::model

