/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Room.h
 *
 * 
 */

#ifndef Room_H_
#define Room_H_


#include <string>
#include "Page.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Room
{
public:
    Room();
    virtual ~Room() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Room& rhs) const;
    bool operator!=(const Room& rhs) const;

    /////////////////////////////////////////////
    /// Room members

    /// <summary>
    /// 
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<org::openapitools::server::model::Page> getPages() const;
    void setPages(std::vector<org::openapitools::server::model::Page> const& value);

    friend  void to_json(nlohmann::json& j, const Room& o);
    friend  void from_json(const nlohmann::json& j, Room& o);
protected:
    std::string m_Id;

    std::vector<org::openapitools::server::model::Page> m_Pages;

    
};

} // namespace org::openapitools::server::model

#endif /* Room_H_ */
