/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Shape.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Shape::Shape()
{
    m_Id = "";
    m_Type = "";
    m_ShapeType = "";
    m_Angle = 0.0;
    
}

void Shape::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Shape::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Shape::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Shape" : pathPrefix;

                         
    
    /* Box */ {
        const std::vector<double>& value = m_Box;
        const std::string currentValuePath = _pathPrefix + ".box";
                
        
        if (value.size() < 4)
        {
            success = false;
            msg << currentValuePath << ": must have at least 4 elements;";
        }
        if (value.size() > 4)
        {
            success = false;
            msg << currentValuePath << ": must have at most 4 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const double& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
    
    return success;
}

bool Shape::operator==(const Shape& rhs) const
{
    return
    
    
    (getId() == rhs.getId())
     &&
    
    (getType() == rhs.getType())
     &&
    
    (getShapeType() == rhs.getShapeType())
     &&
    
    (getAngle() == rhs.getAngle())
     &&
    
    (getBox() == rhs.getBox())
    
    
    ;
}

bool Shape::operator!=(const Shape& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Shape& o)
{
    j = nlohmann::json::object();
    j["id"] = o.m_Id;
    j["type"] = o.m_Type;
    j["shapeType"] = o.m_ShapeType;
    j["angle"] = o.m_Angle;
    j["box"] = o.m_Box;
    
}

void from_json(const nlohmann::json& j, Shape& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("type").get_to(o.m_Type);
    j.at("shapeType").get_to(o.m_ShapeType);
    j.at("angle").get_to(o.m_Angle);
    j.at("box").get_to(o.m_Box);
    
}

std::string Shape::getId() const
{
    return m_Id;
}
void Shape::setId(std::string const& value)
{
    m_Id = value;
}
std::string Shape::getType() const
{
    return m_Type;
}
void Shape::setType(std::string const& value)
{
    m_Type = value;
}
std::string Shape::getShapeType() const
{
    return m_ShapeType;
}
void Shape::setShapeType(std::string const& value)
{
    m_ShapeType = value;
}
double Shape::getAngle() const
{
    return m_Angle;
}
void Shape::setAngle(double const value)
{
    m_Angle = value;
}
std::vector<double> Shape::getBox() const
{
    return m_Box;
}
void Shape::setBox(std::vector<double> const value)
{
    m_Box = value;
}


} // namespace org::openapitools::server::model

