/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Stroke.h
 *
 * 
 */

#ifndef Stroke_H_
#define Stroke_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Stroke
{
public:
    Stroke();
    virtual ~Stroke() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Stroke& rhs) const;
    bool operator!=(const Stroke& rhs) const;

    /////////////////////////////////////////////
    /// Stroke members

    /// <summary>
    /// Universal ID
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);
    /// <summary>
    /// Format: [minx, miny, maxx, maxy]
    /// </summary>
    std::vector<double> getBox() const;
    void setBox(std::vector<double> const value);
    /// <summary>
    /// list of points, in the form x1, y1, x2, y2, ...
    /// </summary>
    std::vector<double> getPoints() const;
    void setPoints(std::vector<double> const value);

    friend  void to_json(nlohmann::json& j, const Stroke& o);
    friend  void from_json(const nlohmann::json& j, Stroke& o);
protected:
    std::string m_Id;

    std::string m_Type;

    std::vector<double> m_Box;

    std::vector<double> m_Points;

    
};

} // namespace org::openapitools::server::model

#endif /* Stroke_H_ */
