/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Symbol.h
 *
 * 
 */

#ifndef Symbol_H_
#define Symbol_H_


#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  Symbol
{
public:
    Symbol();
    virtual ~Symbol() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Symbol& rhs) const;
    bool operator!=(const Symbol& rhs) const;

    /////////////////////////////////////////////
    /// Symbol members

    /// <summary>
    /// Universal ID
    /// </summary>
    std::string getId() const;
    void setId(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getType() const;
    void setType(std::string const& value);
    /// <summary>
    /// string
    /// </summary>
    std::string getSymbolRes() const;
    void setSymbolRes(std::string const& value);
    /// <summary>
    /// In degrees
    /// </summary>
    double getAngle() const;
    void setAngle(double const value);
    bool angleIsSet() const;
    void unsetAngle();
    /// <summary>
    /// Format: [minx, miny, maxx, maxy]
    /// </summary>
    std::vector<double> getBox() const;
    void setBox(std::vector<double> const value);

    friend  void to_json(nlohmann::json& j, const Symbol& o);
    friend  void from_json(const nlohmann::json& j, Symbol& o);
protected:
    std::string m_Id;

    std::string m_Type;

    std::string m_SymbolRes;

    double m_Angle;
    bool m_AngleIsSet;
    std::vector<double> m_Box;

    
};

} // namespace org::openapitools::server::model

#endif /* Symbol_H_ */
