/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Symbol.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Symbol::Symbol()
{
    m_Id = "";
    m_Type = "";
    m_SymbolRes = "";
    m_Angle = 0.0;
    m_AngleIsSet = false;
    
}

void Symbol::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Symbol::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Symbol::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Symbol" : pathPrefix;

                         
    
    /* Box */ {
        const std::vector<double>& value = m_Box;
        const std::string currentValuePath = _pathPrefix + ".box";
                
        
        if (value.size() < 4)
        {
            success = false;
            msg << currentValuePath << ": must have at least 4 elements;";
        }
        if (value.size() > 4)
        {
            success = false;
            msg << currentValuePath << ": must have at most 4 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const double& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
    
    return success;
}

bool Symbol::operator==(const Symbol& rhs) const
{
    return
    
    
    (getId() == rhs.getId())
     &&
    
    (getType() == rhs.getType())
     &&
    
    (getSymbolRes() == rhs.getSymbolRes())
     &&
    
    
    ((!angleIsSet() && !rhs.angleIsSet()) || (angleIsSet() && rhs.angleIsSet() && getAngle() == rhs.getAngle())) &&
    
    (getBox() == rhs.getBox())
    
    
    ;
}

bool Symbol::operator!=(const Symbol& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Symbol& o)
{
    j = nlohmann::json::object();
    j["id"] = o.m_Id;
    j["type"] = o.m_Type;
    j["symbolRes"] = o.m_SymbolRes;
    if(o.angleIsSet())
        j["angle"] = o.m_Angle;
    j["box"] = o.m_Box;
    
}

void from_json(const nlohmann::json& j, Symbol& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("type").get_to(o.m_Type);
    j.at("symbolRes").get_to(o.m_SymbolRes);
    if(j.find("angle") != j.end())
    {
        j.at("angle").get_to(o.m_Angle);
        o.m_AngleIsSet = true;
    } 
    j.at("box").get_to(o.m_Box);
    
}

std::string Symbol::getId() const
{
    return m_Id;
}
void Symbol::setId(std::string const& value)
{
    m_Id = value;
}
std::string Symbol::getType() const
{
    return m_Type;
}
void Symbol::setType(std::string const& value)
{
    m_Type = value;
}
std::string Symbol::getSymbolRes() const
{
    return m_SymbolRes;
}
void Symbol::setSymbolRes(std::string const& value)
{
    m_SymbolRes = value;
}
double Symbol::getAngle() const
{
    return m_Angle;
}
void Symbol::setAngle(double const value)
{
    m_Angle = value;
    m_AngleIsSet = true;
}
bool Symbol::angleIsSet() const
{
    return m_AngleIsSet;
}
void Symbol::unsetAngle()
{
    m_AngleIsSet = false;
}
std::vector<double> Symbol::getBox() const
{
    return m_Box;
}
void Symbol::setBox(std::vector<double> const value)
{
    m_Box = value;
}


} // namespace org::openapitools::server::model

