/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "TextBox.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

TextBox::TextBox()
{
    m_Id = "";
    m_Type = "";
    m_Text = "";
    
}

void TextBox::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool TextBox::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool TextBox::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "TextBox" : pathPrefix;

                 
    
    /* Box */ {
        const std::vector<double>& value = m_Box;
        const std::string currentValuePath = _pathPrefix + ".box";
                
        
        if (value.size() < 4)
        {
            success = false;
            msg << currentValuePath << ": must have at least 4 elements;";
        }
        if (value.size() > 4)
        {
            success = false;
            msg << currentValuePath << ": must have at most 4 elements;";
        }
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const double& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        
 
                i++;
            }
        }

    }
        
    return success;
}

bool TextBox::operator==(const TextBox& rhs) const
{
    return
    
    
    (getId() == rhs.getId())
     &&
    
    (getType() == rhs.getType())
     &&
    
    (getBox() == rhs.getBox())
     &&
    
    (getText() == rhs.getText())
    
    
    ;
}

bool TextBox::operator!=(const TextBox& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TextBox& o)
{
    j = nlohmann::json::object();
    j["id"] = o.m_Id;
    j["type"] = o.m_Type;
    j["box"] = o.m_Box;
    j["text"] = o.m_Text;
    
}

void from_json(const nlohmann::json& j, TextBox& o)
{
    j.at("id").get_to(o.m_Id);
    j.at("type").get_to(o.m_Type);
    j.at("box").get_to(o.m_Box);
    j.at("text").get_to(o.m_Text);
    
}

std::string TextBox::getId() const
{
    return m_Id;
}
void TextBox::setId(std::string const& value)
{
    m_Id = value;
}
std::string TextBox::getType() const
{
    return m_Type;
}
void TextBox::setType(std::string const& value)
{
    m_Type = value;
}
std::vector<double> TextBox::getBox() const
{
    return m_Box;
}
void TextBox::setBox(std::vector<double> const value)
{
    m_Box = value;
}
std::string TextBox::getText() const
{
    return m_Text;
}
void TextBox::setText(std::string const& value)
{
    m_Text = value;
}


} // namespace org::openapitools::server::model

