/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "User.h"
#include "Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

User::User()
{
    m_Username = "";
    m_RoomId = "";
    m_RoomIdIsSet = false;
    m_SessionId = "";
    m_SessionIdIsSet = false;
    m_IsOwner = false;
    m_IsOwnerIsSet = false;
    
}

void User::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool User::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool User::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "User" : pathPrefix;

             
    if (roomIdIsSet())
    {
        const std::string& value = m_RoomId;
        const std::string currentValuePath = _pathPrefix + ".roomId";
                
        
        if (value.length() < 5)
        {
            success = false;
            msg << currentValuePath << ": must be at least 5 characters long;";
        }
        if (value.length() > 5)
        {
            success = false;
            msg << currentValuePath << ": must be at most 5 characters long;";
        }

    }
            
    return success;
}

bool User::operator==(const User& rhs) const
{
    return
    
    
    (getUsername() == rhs.getUsername())
     &&
    
    
    ((!roomIdIsSet() && !rhs.roomIdIsSet()) || (roomIdIsSet() && rhs.roomIdIsSet() && getRoomId() == rhs.getRoomId())) &&
    
    
    ((!sessionIdIsSet() && !rhs.sessionIdIsSet()) || (sessionIdIsSet() && rhs.sessionIdIsSet() && getSessionId() == rhs.getSessionId())) &&
    
    
    ((!isOwnerIsSet() && !rhs.isOwnerIsSet()) || (isOwnerIsSet() && rhs.isOwnerIsSet() && isIsOwner() == rhs.isIsOwner()))
    
    ;
}

bool User::operator!=(const User& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const User& o)
{
    j = nlohmann::json::object();
    j["username"] = o.m_Username;
    if(o.roomIdIsSet())
        j["roomId"] = o.m_RoomId;
    if(o.sessionIdIsSet())
        j["sessionId"] = o.m_SessionId;
    if(o.isOwnerIsSet())
        j["isOwner"] = o.m_IsOwner;
    
}

void from_json(const nlohmann::json& j, User& o)
{
    j.at("username").get_to(o.m_Username);
    if(j.find("roomId") != j.end())
    {
        j.at("roomId").get_to(o.m_RoomId);
        o.m_RoomIdIsSet = true;
    } 
    if(j.find("sessionId") != j.end())
    {
        j.at("sessionId").get_to(o.m_SessionId);
        o.m_SessionIdIsSet = true;
    } 
    if(j.find("isOwner") != j.end())
    {
        j.at("isOwner").get_to(o.m_IsOwner);
        o.m_IsOwnerIsSet = true;
    } 
    
}

std::string User::getUsername() const
{
    return m_Username;
}
void User::setUsername(std::string const& value)
{
    m_Username = value;
}
std::string User::getRoomId() const
{
    return m_RoomId;
}
void User::setRoomId(std::string const& value)
{
    m_RoomId = value;
    m_RoomIdIsSet = true;
}
bool User::roomIdIsSet() const
{
    return m_RoomIdIsSet;
}
void User::unsetRoomId()
{
    m_RoomIdIsSet = false;
}
std::string User::getSessionId() const
{
    return m_SessionId;
}
void User::setSessionId(std::string const& value)
{
    m_SessionId = value;
    m_SessionIdIsSet = true;
}
bool User::sessionIdIsSet() const
{
    return m_SessionIdIsSet;
}
void User::unsetSessionId()
{
    m_SessionIdIsSet = false;
}
bool User::isIsOwner() const
{
    return m_IsOwner;
}
void User::setIsOwner(bool const value)
{
    m_IsOwner = value;
    m_IsOwnerIsSet = true;
}
bool User::isOwnerIsSet() const
{
    return m_IsOwnerIsSet;
}
void User::unsetIsOwner()
{
    m_IsOwnerIsSet = false;
}


} // namespace org::openapitools::server::model

