/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * User.h
 *
 * 
 */

#ifndef User_H_
#define User_H_


#include <string>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// 
/// </summary>
class  User
{
public:
    User();
    virtual ~User() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const User& rhs) const;
    bool operator!=(const User& rhs) const;

    /////////////////////////////////////////////
    /// User members

    /// <summary>
    /// 
    /// </summary>
    std::string getUsername() const;
    void setUsername(std::string const& value);
    /// <summary>
    /// 
    /// </summary>
    std::string getRoomId() const;
    void setRoomId(std::string const& value);
    bool roomIdIsSet() const;
    void unsetRoomId();
    /// <summary>
    /// 
    /// </summary>
    std::string getSessionId() const;
    void setSessionId(std::string const& value);
    bool sessionIdIsSet() const;
    void unsetSessionId();
    /// <summary>
    /// 
    /// </summary>
    bool isIsOwner() const;
    void setIsOwner(bool const value);
    bool isOwnerIsSet() const;
    void unsetIsOwner();

    friend  void to_json(nlohmann::json& j, const User& o);
    friend  void from_json(const nlohmann::json& j, User& o);
protected:
    std::string m_Username;

    std::string m_RoomId;
    bool m_RoomIdIsSet;
    std::string m_SessionId;
    bool m_SessionIdIsSet;
    bool m_IsOwner;
    bool m_IsOwnerIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* User_H_ */
