/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RoomApi.h
 *
 * 
 */

#ifndef RoomApi_H_
#define RoomApi_H_


#include "ApiBase.h"

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "Page.h"
#include "Room.h"
#include "User.h"
#include <string>

namespace org::openapitools::server::api
{

class  RoomApi : public ApiBase {
public:
    explicit RoomApi(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~RoomApi() override = default;
    void init() override;

    static const std::string base;

private:
    void setupRoutes();

    void rooms_post_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void rooms_room_id_delete_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void rooms_room_id_export_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void rooms_room_id_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void rooms_room_id_pages_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void rooms_room_id_users_get_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);
    void room_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response);

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleParsingException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during Parameter parsing and validation.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual void handleOperationException(const std::exception& ex, Pistache::Http::ResponseWriter &response) const noexcept;

    /// <summary>
    /// Helper function to handle unexpected Exceptions during processing of the request in handler functions.
    /// May be overridden to return custom error formats. This is called inside a catch block.
    /// Important: When overriding, do not call `throw ex;`, but instead use `throw;`.
    /// </summary>
    virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(const std::exception& ex) const noexcept;

    /// <summary>
    /// Create a room
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="user"></param>
    virtual void rooms_post(const org::openapitools::server::model::User &user, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Delete the room
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="roomId">The room&#39;s ID</param>
    virtual void rooms_room_id_delete(const std::string &roomId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// export the room as pdf or as a json
    /// </remarks>
    /// <param name="roomId">The room&#39;s ID</param>
    virtual void rooms_room_id_export_get(const std::string &roomId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Get the current state of room by its id
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="roomId">The room&#39;s ID</param>
    virtual void rooms_room_id_get(const std::string &roomId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Get the current state of a page by its id
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="roomId">The room&#39;s ID</param>
    virtual void rooms_room_id_pages_get(const std::string &roomId, Pistache::Http::ResponseWriter &response) = 0;
    /// <summary>
    /// Get a list of users in a room
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="roomId">The room&#39;s ID</param>
    virtual void rooms_room_id_users_get(const std::string &roomId, Pistache::Http::ResponseWriter &response) = 0;

};

} // namespace org::openapitools::server::api

#endif /* RoomApi_H_ */

