/**
* noteworthy web service
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* RoomApiImpl.h
*
* 
*/

#ifndef ROOM_API_IMPL_H_
#define ROOM_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <RoomApi.h>


#include "Page.h"
#include "Room.h"
#include "User.h"
#include <string>

namespace org::openapitools::server::api
{

using namespace org::openapitools::server::model;

class  RoomApiImpl : public org::openapitools::server::api::RoomApi {
public:
    explicit RoomApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
    ~RoomApiImpl() override = default;

    void rooms_post(const User &user, Pistache::Http::ResponseWriter &response);
    void rooms_room_id_delete(const std::string &roomId, Pistache::Http::ResponseWriter &response);
    void rooms_room_id_export_get(const std::string &roomId, Pistache::Http::ResponseWriter &response);
    void rooms_room_id_get(const std::string &roomId, Pistache::Http::ResponseWriter &response);
    void rooms_room_id_pages_get(const std::string &roomId, Pistache::Http::ResponseWriter &response);
    void rooms_room_id_users_get(const std::string &roomId, Pistache::Http::ResponseWriter &response);

};

} // namespace org::openapitools::server::api



#endif
